apiVersion: v1
kind: ResourceQuota
metadata:
  name: helpme-api-quota
  namespace: helpme
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 8Gi
    limits.cpu: "10"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    services.loadbalancers: "1"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values: ["high"]