apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: helpme
data:
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_LOG_SEGMENT_BYTES: "1073741824"
  KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
  KAFKA_NUM_PARTITIONS: "3"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_MIN_INSYNC_REPLICAS: "1"
  KAFKA_MESSAGE_MAX_BYTES: "10485760"
  KAFKA_COMPRESSION_TYPE: "snappy"