apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  namespace: helpme
type: Opaque
stringData:
  INFLUXDB_DB: helpme_metrics
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: influx_secure_password_2024
  INFLUXDB_USER: helpme_user
  INFLUXDB_USER_PASSWORD: influx_user_password_2024
  INFLUXDB_HTTP_AUTH_ENABLED: "true"