apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: helpme
  labels:
    app: influxdb
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"
    
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      query-log-enabled = true
      cache-max-memory-size = 1073741824
      cache-snapshot-memory-size = 26214400
      cache-snapshot-write-cold-duration = "10m"
      compact-full-write-cold-duration = "4h"
      max-series-per-database = 1000000
      max-values-per-tag = 100000
    
    [coordinator]
      write-timeout = "10s"
      max-concurrent-queries = 0
      query-timeout = "0s"
      log-queries-after = "0s"
      max-select-point = 0
      max-select-series = 0
      max-select-buckets = 0
    
    [retention]
      enabled = true
      check-interval = "30m"
    
    [http]
      enabled = true
      bind-address = ":8086"
      auth-enabled = true
      log-enabled = true
      write-tracing = false
      https-enabled = false
      max-row-limit = 10000
      max-connection-limit = 0
      unix-socket-enabled = false
    
    [logging]
      format = "auto"
      level = "info"