apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: helpme
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: mongo_secure_password_2024
  MONGODB_URI: mongodb://admin:mongo_secure_password_2024@mongodb-service:27017/helpme_audit?authSource=admin