apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: helpme
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: client
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: follower
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: election
  selector:
    app: zookeeper